# Generated by Django 3.1.5 on 2021-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(upload_to='articles/%Y/%m/%d'),
        ),
    ]
