# Generated by Django 3.1.5 on 2021-01-22 19:57

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
