# Generated by Django 3.1.5 on 2021-01-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
