# Generated by Django 3.1.5 on 2021-02-07 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210129_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downVotes',
            field=models.ManyToManyField(blank=True, related_name='down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='articles.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upVotes',
            field=models.ManyToManyField(blank=True, related_name='up_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
